// Utility functions for generating court-admissible PDF reports
export interface ChainOfCustodyEntry {
  action: string
  actor: string
  timestamp: string
  details: string
  status: string
}

export interface EvidenceData {
  caseNumber: string
  itemNumber: string
  description: string
  type: string
  recordedBy: string
  recordedDate: string
  hash: string
  ipaRecord: string
  canisterId: string
  chainOfCustody: ChainOfCustodyEntry[]
}

export function generatePDFContent(evidence: EvidenceData): string {
  const timestamp = new Date().toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    timeZone: "UTC",
  })

  let content = `
CHAIN OF CUSTODY REPORT
Lex Veritas 2.0 - Digital Evidence Management System
Generated: ${timestamp}

================================================================================
EVIDENCE SUMMARY
================================================================================

Case Number:           ${evidence.caseNumber}
Evidence Item #:       ${evidence.itemNumber}
Description:           ${evidence.description}
Evidence Type:         ${evidence.type}
Initial Recording By:  ${evidence.recordedBy}
Recording Date:        ${evidence.recordedDate}

================================================================================
CRYPTOGRAPHIC VERIFICATION
================================================================================

SHA-256 Hash:          ${evidence.hash}
Story Protocol Record: ${evidence.ipaRecord}
ICP Canister ID:       ${evidence.canisterId}

This evidence has been recorded on an immutable blockchain ledger via Story Protocol
and stored on the Internet Computer Protocol (ICP) network. The cryptographic hash
ensures the integrity and authenticity of the evidence.

================================================================================
CHAIN OF CUSTODY HISTORY
================================================================================

`

  evidence.chainOfCustody.forEach((entry, index) => {
    content += `
[${index + 1}] ${entry.action}
    Actor:      ${entry.actor}
    Timestamp:  ${entry.timestamp}
    Status:     ${entry.status}
    Details:    ${entry.details}

`
  })

  content += `
================================================================================
LEGAL CERTIFICATION
================================================================================

This Chain of Custody Report certifies that the above-referenced evidence has been
maintained in an unbroken chain of custody from the time of initial collection through
the present date. All transfers, actions, and interactions with this evidence have been
recorded on an immutable, cryptographically-signed ledger.

This report is generated by the Lex Veritas 2.0 Digital Evidence Management System
and is suitable for presentation in court proceedings.

Generated by: Lex Veritas 2.0
System Version: 2.0
Report Type: Chain of Custody Report
`

  return content
}

export function downloadReport(content: string, caseNumber: string, itemNumber: string) {
  const filename = `COC_${caseNumber}_Item${itemNumber}_${new Date().toISOString().split("T")[0]}.txt`
  const element = document.createElement("a")
  element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content))
  element.setAttribute("download", filename)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}
